version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  bot:
    container_name: bot
    build: ./bot
    environment:
      - BOT_TOKEN=<YOUR_BOT_TOKEN>
      - CHANNELS_TO_SUBSCRIBE=<YOUR_CHANNELS_TO_SUBSCRIBE>
      - BOT_USERNAME=<YOUR_BOT_USERNAME>
      - YOOKASSA_TOKEN=<YOUR_YOOKASSA_TOKEN>
      - YOOKASSA_ID=<YOUR_YOOKASSA_ID>
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres

  admin_panel:
    container_name: admin_panel
    build: ./admin_panel
    environment:
      - BOT_TOKEN=<YOUR_BOT_TOKEN>
      - POSTGRES_DB=testtask
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - postgres
